name: news_wave_admin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.67.0
  provider: ^6.1.2
  flutter_bloc: ^8.1.5
  auto_route: ^8.0.3
  flutter_screenutil: ^5.9.0
  flutter_localization: ^0.2.0
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  image_picker: ^1.1.1
  file_picker: ^8.0.3
  typed_data: ^1.3.2
  firebase_storage: ^11.7.5
  fluttertoast: ^8.2.5
  cloud_firestore: ^4.17.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_gen_runner:
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/

