name: news_wave_admin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.67.0
  provider: ^6.1.2
  flutter_bloc: ^8.1.5
  auto_route: ^8.0.3
  flutter_screenutil: ^5.9.0
  flutter_localization: ^0.2.0
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner:
  flutter_gen_runner:

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/

